
services:
  shopcart_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_service
    command: ["sh", "/app/entrypoint.sh"]
    ports:
      - "8008:8000"
    env_file:
      - .env
    environment:
      - ENV=development
    depends_on:
      - db
    working_dir: /app
    volumes:
    #mount local files so Uvicorn sees changes instantly
      - ./src:/app/src:rw
      - ./uv.lock:/app/uv.lock:rw
      - ./pyproject.toml:/app/pyproject.toml:rw
      - ./.cache/uv:/home/appuser/.cache/uv  # fixing permission denied errors
    restart: unless-stopped
    networks:
      - internal_net
      - shared_network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - internal_net

networks:
  internal_net:
  # internal: true
    driver: bridge
  shared_network:
    driver: bridge
    name: shared_network

volumes:
  postgres_data:
