# Generated by Django 5.2.8 on 2025-11-06 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField(verbose_name='Order ID')),
                ('product_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Product ID')),
                ('product_variation', models.CharField(max_length=36, verbose_name='Product Variation ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.BigIntegerField(verbose_name='Price (in qepik)')),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Cancelled')], default=1, verbose_name='Status')),
                ('user_id', models.CharField(max_length=36, verbose_name='User ID (customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name_plural': 'ShopOrderItems',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['shop', 'status'], name='shops_shopo_shop_id_9368c7_idx'), models.Index(fields=['order_id'], name='shops_shopo_order_i_950395_idx')],
            },
        ),
    ]
