# Generated by Django 5.2.7 on 2025-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
    ]
