# Generated by Django 5.2.7 on 2025-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation',
            field=models.CharField(max_length=36),
        ),
    ]
