# Generated by Django 5.2.7 on 2025-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
