services:
  redis:
    image: redis:7.2
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

    networks:
      - internal_net
      - shared_network

networks:
  internal_net:
  # internal: true
    driver: bridge
  shared_network:
    external: true
    name: shared_network

volumes:
  redis_data:
